const BaseService = require('../../base/baseService');
const argon2 = require('argon2');

/**
 * SignupService
 * Orchestrates user registration business logic.
 */
class SignupService extends BaseService {
  constructor(signupRepository) {
    super(signupRepository);
  }

  /**
   * Registers a new user account.
   *
   * Steps:
   *  1. Validate email uniqueness
   *  2. Hash password with argon2 (same library used throughout the app)
   *  3. Generate UUIDs via BaseService.generateUuid()
   *  4. Insert `users` record
   *  5. Insert `user_details` record
   *
   * Passwords are NEVER stored in plain text.
   * UUIDs are generated by BaseService — never by the frontend.
   */
  async processSignup({ email, password, firstName, lastName, displayName, phoneNumber, dateOfBirth, gender, language }) {
    // 1. Email uniqueness check
    const emailExists = await this.repository.emailExists(email);
    if (emailExists) {
      throw new Error('An account with this email already exists.');
    }

    // 2. Hash password
    const passwordHash = await argon2.hash(password);

    // 3. UUIDs
    const userUuid = this.generateUuid();
    const userDetailsUuid = this.generateUuid();
    const userRoleEntryUuid = this.generateUuid();

    // 4. Resolve the default 'user' role (outside transaction — read-only)
    const userRole = await this.repository.getRoleByName('user');
    if (!userRole) {
      throw new Error('Default \'user\' role not found. Please ensure it exists in the roles table.');
    }

    // 5. Insert users, user_details and user_roles atomically
    await this.repository.queryHelper.transaction(async (trx) => {
      await this.repository.createUser(
        { uuid: userUuid, email, passwordHash, language: language || 'en' },
        trx
      );
      await this.repository.createUserDetails(
        {
          uuid: userDetailsUuid,
          userUuid,
          firstName,
          lastName,
          displayName,
          phoneNumber,
          dateOfBirth: dateOfBirth || null,
          gender,
        },
        trx
      );
      await this.repository.assignUserRole(
        { uuid: userRoleEntryUuid, userUuid, roleUuid: userRole.uuid },
        trx
      );
    });

    return { message: 'Account created successfully. Please sign in.' };
  }
}

module.exports = SignupService;
